### ISSUE TITLE
Subtext position differs by a bug with word wrap

### ISSUE THREAD

**Issue by cozyplanes** [devBanner/devBanner#29]
The position for subtext differs by some unknown reason

maybe the text length is effected, or some bug while fetching
Was there something changed while the word wrap was merged? @Kimmax @Mitch528 

----

(i) dfox and kimmax subtext position is the same

(ii) trogus and alexdelarge subtext position is the same
 
however the subtext position for (i) and (ii) differs

**Comment by Mitch528** [comment]
Yeah, the word-wrapping addition in #28 caused this. I was trying to solve an issue where the username text would slightly overlap the subtext when doing the word-wrapping that occurred in some cases. To solve this, I shifted the Y position by adding the height of the username text instead of by the username font size.

Before:
![alexdelarge_before](https://user-images.githubusercontent.com/932976/34056530-31b50dc2-e188-11e7-8f7b-b97db841d30c.png)

After:
![alexdelarge_after](https://user-images.githubusercontent.com/932976/34056542-402fe476-e188-11e7-8822-bbf859d77852.png)

**Comment by Kimmax** [comment]
Since #30 is merged and deployed this should be taken care off

**Comment by cozyplanes** [comment]
will check and close

**Comment by cozyplanes** [comment]
Seems it is fixed, lookin' beautiful!
